"""
Contenus « Bien-être & Mindset » : parcours de 7 jours et cartes du jour.

Principes d'écriture : tutoiement, 5 minutes maximum par exercice, une idée
claire, une action concrète. Outils de recul et de pratique — jamais de
diagnostic ni de promesse thérapeutique.
Chaque jour : titre, idee (2-3 phrases), exercice (consigne), questions (réponses écrites).
"""

PARCOURS = [
    {
        "id": "oser-vendre",
        "titre": "Oser vendre",
        "sous_titre": "Parler de ton offre sans te sentir « commercial »",
        "pour_qui": "Tu repousses les relances, tu sous-estimes tes prix ou tu as peur de déranger.",
        "couleur": "#DEC2A3",
        "jours": [
            {"titre": "Ce que tu vends vraiment",
             "idee": "Tes clients n'achètent pas une prestation, ils achètent un changement dans leur situation. Quand tu parles de ce changement, vendre devient rendre service.",
             "exercice": "Pense à ton dernier client satisfait. Décris sa situation avant et après t'avoir rencontré.",
             "questions": ["Avant, il ou elle vivait…", "Après, il ou elle peut…", "En une phrase : j'aide … à … sans …"]},
            {"titre": "Ta peur, en clair",
             "idee": "La peur de vendre est souvent une peur d'être rejeté personnellement. Or un « non » porte sur un moment et un besoin, pas sur ta valeur.",
             "exercice": "Écris ta pire crainte quand tu proposes ton offre, puis ce qui se passerait réellement si elle arrivait.",
             "questions": ["Ma crainte quand je propose mon offre :", "Ce qui se passerait vraiment :", "Ce que je me dirais si c'était un ami qui vivait ça :"]},
            {"titre": "Tes preuves",
             "idee": "La confiance ne vient pas d'un discours, elle vient de preuves. Tu en as plus que tu ne le crois.",
             "exercice": "Liste trois résultats concrets obtenus pour des clients, même petits (un délai tenu, un problème réglé, un retour positif).",
             "questions": ["Preuve 1 :", "Preuve 2 :", "Preuve 3 :"]},
            {"titre": "Le message de 3 phrases",
             "idee": "Un bon message de prise de contact tient en trois phrases : ce que tu as remarqué chez la personne, ce que tu fais pour des gens comme elle, une question simple.",
             "exercice": "Rédige un message pour un vrai prospect (tu peux partir d'une opportunité de ton Radar).",
             "questions": ["J'ai remarqué que…", "J'aide des … à …", "Ma question simple :"]},
            {"titre": "Le prix, sans t'excuser",
             "idee": "Annoncer son prix en s'excusant invite à négocier. Un prix annoncé calmement, suivi d'un silence, rassure.",
             "exercice": "Écris ta phrase d'annonce de prix, puis lis-la à voix haute trois fois, lentement, sans rien ajouter après.",
             "questions": ["Ma phrase : « Pour cet accompagnement, l'investissement est de … »", "Ce que j'ai ressenti en la disant :"]},
            {"titre": "Une relance qui aide",
             "idee": "Relancer n'est pas insister : c'est rendre service à quelqu'un qui a oublié ou qui hésite. La plupart des ventes se font après la deuxième relance.",
             "exercice": "Choisis une personne à relancer aujourd'hui et envoie un message court qui apporte quelque chose (une ressource, une question, une disponibilité).",
             "questions": ["Qui je relance :", "Ce que je lui apporte :", "C'est envoyé ? (oui / pas encore, pourquoi)"]},
            {"titre": "Ton rituel de vente",
             "idee": "Vendre devient facile quand c'est une habitude courte et régulière plutôt qu'un effort héroïque.",
             "exercice": "Choisis un créneau fixe de 20 minutes par semaine consacré uniquement à proposer, relancer ou demander une recommandation.",
             "questions": ["Mon créneau (jour, heure) :", "Ce que je fais pendant ces 20 minutes :", "Ma plus grande fierté de la semaine :"]},
        ],
    },
    {
        "id": "revenus-irreguliers",
        "titre": "Vivre avec des revenus irréguliers",
        "sous_titre": "Retrouver du calme quand le chiffre d'affaires fait des vagues",
        "pour_qui": "Un mois creux te met en tension, tu ne sais jamais vraiment « combien tu gagnes ».",
        "couleur": "#7C93C3",
        "jours": [
            {"titre": "Ton chiffre de sérénité",
             "idee": "L'angoisse vient souvent du flou. Connaître le montant minimum dont tu as besoin chaque mois transforme une peur diffuse en objectif précis.",
             "exercice": "Calcule ton minimum mensuel : charges pro, cotisations, et la rémunération minimale qui te permet de vivre sereinement.",
             "questions": ["Charges pro par mois :", "Cotisations et impôts estimés :", "Ma rémunération minimale :", "Mon chiffre de sérénité (total) :"]},
            {"titre": "Le coussin",
             "idee": "Une réserve de trésorerie de deux à trois mois de chiffre de sérénité change ta façon de décider : tu refuses les mauvais clients, tu négocies mieux.",
             "exercice": "Regarde ta trésorerie actuelle et calcule combien de mois elle couvre.",
             "questions": ["Ma trésorerie aujourd'hui :", "Elle couvre … mois", "Ce que je mets de côté chaque mois à partir de maintenant :"]},
            {"titre": "Te payer comme un salarié",
             "idee": "Te verser la même somme chaque mois, quel que soit le chiffre du mois, lisse les vagues et protège ta vie perso.",
             "exercice": "Fixe un montant de rémunération fixe et une date de virement mensuelle.",
             "questions": ["Montant fixe que je me verse :", "Date du virement :", "Ce que ça change pour moi :"]},
            {"titre": "Tes sources de revenus",
             "idee": "Dépendre d'un seul client ou d'un seul canal rend chaque mois fragile. Deux ou trois sources, même petites, amortissent les creux.",
             "exercice": "Liste d'où vient ton chiffre d'affaires des trois derniers mois, en pourcentage.",
             "questions": ["Source 1 et part :", "Source 2 et part :", "Une nouvelle source récurrente possible :"]},
            {"titre": "Le mois creux, un outil",
             "idee": "Un mois calme n'est pas un échec : c'est un temps pour prospecter, créer, se former, se reposer. L'important est de le décider au lieu de le subir.",
             "exercice": "Prépare ton « plan mois creux » : ce que tu fais en priorité quand le chiffre baisse.",
             "questions": ["Mes 3 actions de prospection :", "Ce que je crée ou améliore :", "Comment je me repose sans culpabiliser :"]},
            {"titre": "L'argent et toi",
             "idee": "Nos réactions face à l'argent viennent souvent de notre histoire. Les regarder avec bienveillance aide à décider plus froidement.",
             "exercice": "Écris la phrase sur l'argent que tu entendais enfant, puis celle que tu choisis aujourd'hui.",
             "questions": ["La phrase que j'entendais :", "Ce qu'elle me fait faire aujourd'hui :", "La phrase que je choisis :"]},
            {"titre": "Ton tableau de bord",
             "idee": "Regarder ses chiffres une fois par semaine, toujours au même moment, remplace l'inquiétude permanente par un rendez-vous.",
             "exercice": "Choisis ton moment hebdomadaire et mets à jour ton Pouls business dans Zayado.",
             "questions": ["Mon rendez-vous chiffres (jour, heure) :", "Les 3 chiffres que je regarde :", "Ce que je ressens maintenant face à mes revenus :"]},
        ],
    },
    {
        "id": "dire-non",
        "titre": "Savoir dire non",
        "sous_titre": "Protéger ton temps, ton énergie et tes priorités",
        "pour_qui": "Tu acceptes trop, tu finis tard, tes priorités passent après celles des autres.",
        "couleur": "#7A9E7E",
        "jours": [
            {"titre": "Ce que coûte un oui",
             "idee": "Chaque oui à quelque chose est un non à autre chose : ton temps, ta famille, ton projet principal.",
             "exercice": "Repense à un oui récent que tu regrettes. Qu'est-ce qu'il t'a coûté ?",
             "questions": ["Le oui que je regrette :", "Ce qu'il m'a coûté :", "Ce que j'aurais pu dire à la place :"]},
            {"titre": "Tes 3 priorités",
             "idee": "Dire non devient simple quand tes priorités sont claires. Elles deviennent ton filtre.",
             "exercice": "Écris tes trois priorités du trimestre (tu peux reprendre tes objectifs Zayado).",
             "questions": ["Priorité 1 :", "Priorité 2 :", "Priorité 3 :"]},
            {"titre": "Le non poli",
             "idee": "Un non respectueux tient en trois temps : remercier, refuser clairement, proposer une alternative si tu le souhaites.",
             "exercice": "Rédige ton modèle de refus, prêt à réutiliser.",
             "questions": ["Merci pour…", "Je ne vais pas pouvoir…", "En revanche, je peux… / je vous conseille…"]},
            {"titre": "Le délai de réponse",
             "idee": "Répondre « je vous redis demain » te protège des oui impulsifs. Le temps de réflexion est un droit.",
             "exercice": "Choisis ta phrase pour gagner du temps et engage-toi à l'utiliser cette semaine.",
             "questions": ["Ma phrase pour gagner du temps :", "La prochaine situation où je l'utiliserai :"]},
            {"titre": "Tes horaires",
             "idee": "Une heure de fin de journée claire protège ton énergie autant qu'un rendez-vous client.",
             "exercice": "Fixe ton heure de fin et le rituel qui marque la fin de ta journée de travail.",
             "questions": ["Mon heure de fin :", "Mon rituel de fin de journée :", "Ce que je fais de ce temps retrouvé :"]},
            {"titre": "Le client qui épuise",
             "idee": "Certains clients coûtent plus d'énergie qu'ils ne rapportent. Les identifier permet d'ajuster le cadre ou de s'en séparer proprement.",
             "exercice": "Pense à une relation professionnelle qui te pèse. Qu'est-ce qui la rendrait acceptable ?",
             "questions": ["La relation qui me pèse :", "Le cadre qui la rendrait acceptable :", "Ma prochaine étape :"]},
            {"titre": "Ton premier vrai non",
             "idee": "La première fois est la plus difficile. Ensuite, dire non devient une compétence comme une autre.",
             "exercice": "Dis non à une demande cette semaine en utilisant ton modèle, puis note ce qui s'est passé.",
             "questions": ["À quoi j'ai dit non :", "Comment ça s'est passé :", "Ce que j'ai gagné :"]},
        ],
    },
    {
        "id": "rebondir",
        "titre": "Rebondir après un refus",
        "sous_titre": "Transformer un « non » en apprentissage et en élan",
        "pour_qui": "Un refus, un devis perdu ou un silence te fait douter pendant des jours.",
        "couleur": "#B9524E",
        "jours": [
            {"titre": "Accueillir le refus",
             "idee": "La déception est normale. La reconnaître, plutôt que la cacher, permet de la traverser plus vite.",
             "exercice": "Nomme ce que tu ressens après ce refus, sans te juger.",
             "questions": ["Le refus :", "Ce que je ressens :", "Ce dont j'ai besoin maintenant :"]},
            {"titre": "Séparer les faits",
             "idee": "Après un refus, on invente souvent une histoire (« je suis trop cher », « je ne suis pas légitime »). Revenir aux faits calme le mental.",
             "exercice": "Sépare ce qui a été dit réellement de ce que tu as imaginé.",
             "questions": ["Ce qui a été dit ou écrit :", "Ce que je me suis raconté :", "Une autre explication possible :"]},
            {"titre": "Demander un retour",
             "idee": "Un refus bien accueilli ouvre souvent la porte à un retour précieux, et parfois à une future collaboration.",
             "exercice": "Écris un message court pour remercier et demander ce qui aurait fait la différence.",
             "questions": ["Mon message :", "Envoyé ? (oui / pas encore)"]},
            {"titre": "Ce que j'apprends",
             "idee": "Chaque refus contient une information : le prix, le moment, la cible, le message.",
             "exercice": "Tire une leçon concrète de ce refus.",
             "questions": ["Ce qui n'a pas fonctionné :", "Ce que je change pour la prochaine fois :"]},
            {"titre": "Tes victoires",
             "idee": "Le cerveau retient davantage les échecs que les succès. Les relire rééquilibre la balance.",
             "exercice": "Relis tes victoires dans Zayado et écris les trois dont tu es le plus fier.",
             "questions": ["Victoire 1 :", "Victoire 2 :", "Victoire 3 :"]},
            {"titre": "Le prochain pas",
             "idee": "L'élan revient par l'action, même petite. Un seul nouveau contact suffit à relancer la dynamique.",
             "exercice": "Choisis une opportunité dans ton Radar et agis aujourd'hui.",
             "questions": ["L'action choisie :", "Faite ? Comment je me sens après :"]},
            {"titre": "Ta phrase d'appui",
             "idee": "Une phrase simple, relue avant une démarche difficile, rappelle pourquoi tu fais ce métier.",
             "exercice": "Écris ta phrase d'appui et garde-la visible (tu peux l'épingler sur ton Vision Board).",
             "questions": ["Ma phrase d'appui :", "Où je la garde visible :"]},
        ],
    },
]

CARTES = [
    {"id": "trois-victoires", "titre": "Tes 3 victoires d'hier", "idee": "Remarquer ce qui a marché entraîne le cerveau à voir les possibilités plutôt que les obstacles.",
     "exercice": "Note trois choses réussies hier, même minuscules.", "questions": ["1.", "2.", "3."]},
    {"id": "une-seule-chose", "titre": "La seule chose", "idee": "Quand tout semble urgent, une seule action compte vraiment pour avancer vers ta vision.",
     "exercice": "Si tu ne pouvais faire qu'une chose aujourd'hui, laquelle ferait la plus grande différence ?", "questions": ["Ma seule chose aujourd'hui :", "Quand je la fais :"]},
    {"id": "pensee-qui-bloque", "titre": "Une pensée qui bloque", "idee": "Une pensée n'est pas un fait. L'écrire permet de la regarder de l'extérieur.",
     "exercice": "Écris la pensée qui te freine en ce moment, puis une version plus juste.", "questions": ["La pensée :", "Une version plus juste :"]},
    {"id": "energie-agenda", "titre": "Ton énergie, ton agenda", "idee": "Placer les tâches difficiles sur tes heures d'énergie haute est plus efficace que de lutter contre toi-même.",
     "exercice": "Repère ton meilleur moment de la journée et protège-le pour ta tâche la plus importante.", "questions": ["Mon meilleur moment :", "Ce que j'y place demain :"]},
    {"id": "gratitude-client", "titre": "Merci à un client", "idee": "Exprimer sa gratitude renforce la relation et rappelle pourquoi tu fais ce métier.",
     "exercice": "Envoie un message de remerciement sincère à un client ou partenaire.", "questions": ["À qui :", "Ce que je lui dis :"]},
    {"id": "pause-sans-ecran", "titre": "Cinq minutes sans écran", "idee": "Le cerveau a besoin de vrais temps de pause pour trier l'information et retrouver des idées.",
     "exercice": "Fais une pause de cinq minutes sans téléphone ni ordinateur, puis note ce qui t'est venu.", "questions": ["Ce qui m'est venu pendant la pause :"]},
    {"id": "demande-aide", "titre": "Demander de l'aide", "idee": "Entreprendre seul ne veut pas dire tout faire seul. Demander, c'est gagner du temps.",
     "exercice": "Identifie une tâche où quelqu'un pourrait t'aider cette semaine.", "questions": ["La tâche :", "À qui je peux demander :"]},
    {"id": "fierte", "titre": "Ce dont tu es fier", "idee": "Regarder le chemin parcouru donne de la force pour la suite.",
     "exercice": "Compare ta situation d'il y a un an avec celle d'aujourd'hui.", "questions": ["Il y a un an :", "Aujourd'hui :", "Ce dont je suis fier :"]},
    {"id": "limite-du-jour", "titre": "Ta limite du jour", "idee": "Fixer à l'avance ce que tu ne feras pas aujourd'hui te protège de l'épuisement.",
     "exercice": "Choisis une chose que tu ne feras pas aujourd'hui, et assume-la.", "questions": ["Aujourd'hui, je ne fais pas :", "Pourquoi c'est un bon choix :"]},
    {"id": "curiosite", "titre": "Une question à un client", "idee": "Les meilleures idées d'offre viennent souvent d'une simple question posée à un client.",
     "exercice": "Pose aujourd'hui à un client : « Qu'est-ce qui vous aiderait le plus en ce moment ? »", "questions": ["À qui je la pose :", "Sa réponse :"]},
]

CARTE_ALLEGEE = {
    "id": "journee-allegee", "titre": "Journée allégée", "contexte": "Ton énergie est basse depuis quelques jours.",
    "idee": "Ralentir un jour n'est pas perdre du temps : c'est éviter de perdre une semaine. Garde l'essentiel, décale le reste.",
    "exercice": "Choisis la seule tâche indispensable d'aujourd'hui, et ce que tu décales sans culpabiliser.",
    "questions": ["La seule tâche indispensable :", "Ce que je décale :", "Ce que je fais pour recharger :"],
}

# Mini-exercices publics (intégrés dans les articles du Journal Shopify).
MINI = {p["id"]: {"parcours": p["id"], "titre": p["titre"], "sous_titre": p["sous_titre"],
                  "idee": p["jours"][0]["idee"], "exercice": p["jours"][0]["exercice"],
                  "questions": p["jours"][0]["questions"][:3]} for p in PARCOURS}
