import React from "react";
import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import { ArrowRight, BarChart3, Building2, FileText, TrendingUp } from "lucide-react";
import { PublicHeader, UnifiedFooter } from "./LandingHub";
const SERVICES=[
 ["Finance & pilotage","/services/finance-pilotage","Comprendre votre activité, suivre la trésorerie et préparer vos décisions.",BarChart3,"Opéré par Zayado"],
 ["Gestion & délégation","/services/gestion-administrative","Déléguer une partie de l'administratif et remettre du temps dans votre semaine.",FileText,"Zayado + partenaires"],
 ["Création & structuration","/services/creation-structuration","Passer d'une idée ou d'une activité dispersée à une base structurée et exploitable.",Building2,"Parcours accompagné"],
 ["Cession / reprise","/services/cession-reprise","Préparer une transmission ou explorer une reprise avec un premier cadrage clair.",TrendingUp,"Accès prioritaire MyExtension AI"],
];
export default function NosServices(){return <div className="min-h-screen" style={{background:"#f6f3ee"}}><Helmet><title>Services Zayado | Finance, gestion, création & cession</title><meta name="description" content="Zayado accompagne les indépendants et petites structures en finance, gestion, création, structuration, cession et reprise. Commencez par un diagnostic court."/><link rel="canonical" href="https://zayado.net/nos-services"/><meta name="robots" content="index,follow"/></Helmet><PublicHeader/><main><section className="text-white" style={{background:"linear-gradient(120deg,#0c1d33,#1f3a5f)"}}><div className="max-w-6xl mx-auto px-4 md:px-6 py-16 md:py-24"><div className="text-xs uppercase tracking-widest text-[#d4b982]">ZAYADO SERVICES</div><h1 className="mt-4 text-4xl md:text-6xl font-serif max-w-4xl">Une équipe autour de votre activité, sans vous obliger à tout construire seul.</h1><p className="mt-5 text-white/75 text-lg max-w-2xl">Un premier diagnostic de 3 questions vous oriente vers le bon parcours. Quand le service est opéré par Zayado, vous bénéficiez de notre équipe ; quand une expertise externe est nécessaire, nous vous orientons vers le bon partenaire.</p></div></section><section className="max-w-6xl mx-auto px-4 md:px-6 py-14"><div className="grid md:grid-cols-2 gap-5">{SERVICES.map(([t,href,d,I,tag])=><Link to={href} key={href} className="group rounded-[28px] bg-white border border-[#e4dccd] p-7 hover:-translate-y-1 transition"><div className="flex justify-between items-start"><div className="w-12 h-12 rounded-2xl grid place-items-center bg-[#edf2f8] text-[#1f3a5f]"><I size={21}/></div><span className="text-[10px] uppercase tracking-widest rounded-full bg-[#f7f1e5] text-[#8b6f40] px-2.5 py-1">{tag}</span></div><h2 className="mt-5 text-2xl font-serif" style={{color:"#102945"}}>{t}</h2><p className="mt-2 text-sm text-[#6f675d] max-w-lg">{d}</p><div className="mt-5 inline-flex items-center gap-2 text-sm font-semibold" style={{color:"#102945"}}>Voir le parcours <ArrowRight size={15} className="group-hover:translate-x-1 transition"/></div></Link>)}</div></section><section className="max-w-5xl mx-auto px-4 md:px-6 pb-16"><div className="rounded-[28px] bg-[#fbf8f1] border border-[#e4dccd] p-7 md:p-10 text-center"><div className="text-xs uppercase tracking-widest text-[#a18145]">Pourquoi un diagnostic ?</div><h2 className="mt-2 text-3xl font-serif">Parce qu'un bon service commence par un bon cadrage.</h2><p className="mt-3 text-sm text-[#71685d] max-w-2xl mx-auto">Nous évitons le « contactez-nous » générique. Vous décrivez votre situation, nous clarifions le besoin, puis nous orientons vers la bonne réponse.</p><Link to="/services/finance-pilotage" className="inline-flex mt-6 items-center gap-2 rounded-full px-5 py-3 bg-[#102945] text-white text-sm font-semibold">Commencer un diagnostic <ArrowRight size={15}/></Link></div></section></main><UnifiedFooter/></div>}
