import React from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Check, Cloud, Compass, Heart, Lightbulb, MessageCircle, ShieldCheck, Target, Zap } from "lucide-react";
import { MarketingLayout } from "@/components/marketing/MarketingLayout";
import { useSeo } from "@/lib/useSeo";

const FEATURES = [
  { icon: Compass, title: "Vision et objectifs", text: "Transformez votre direction en objectifs et en feuille de route réaliste.", to: "/ia/organisation-entrepreneur" },
  { icon: Check, title: "Actions et priorités", text: "Sachez quelle action faire maintenant sans vous perdre dans une liste infinie.", to: "/ia/organisation-entrepreneur" },
  { icon: Target, title: "Prospection commerciale", text: "Repérez vos prochaines opportunités et préparez vos messages.", to: "/ia/prospection" },
  { icon: Heart, title: "Équilibre du dirigeant", text: "Adaptez votre organisation à votre énergie et à votre réalité.", to: "/ia/equilibre-dirigeant" },
  { icon: MessageCircle, title: "Copilote IA", text: "Clarifiez vos décisions et préparez vos documents avec un assistant contextuel.", to: "/ia/copilote-documents" },
  { icon: Cloud, title: "Documents et cloud", text: "Enregistrez vos documents dans Google Drive, OneDrive ou SharePoint.", to: "/ia/copilote-documents" },
];

const FAQ = [
  ["Qu’est-ce que le Cockpit IA Zayado ?", "C’est un espace de pilotage pour entrepreneurs, freelances et dirigeants de petites entreprises. Il relie vision, objectifs, actions, prospection, énergie et documents."],
  ["L’IA décide-t-elle à ma place ?", "Non. L’IA prépare, structure et propose. Vous gardez la validation finale sur vos décisions et vos actions."],
  ["Le Cockpit IA remplace-t-il un outil de gestion de projet ?", "Il va plus loin qu’une simple liste de tâches en reliant stratégie, exécution, croissance et équilibre. Il peut aussi compléter vos outils existants."],
  ["Puis-je sauvegarder automatiquement mes documents ?", "Oui. Après avoir connecté votre cloud et activé le réglage, les documents peuvent être transmis à Google Drive, OneDrive ou SharePoint."],
  ["Le module équilibre est-il médical ?", "Non. Il aide à observer votre énergie et à ajuster votre organisation. Il ne remplace jamais un professionnel de santé."],
];

export default function IaLanding() {
  useSeo({ title: "Cockpit IA pour entrepreneurs et indépendants | Zayado", description: "Structurez votre vision, organisez vos priorités, développez votre prospection et créez vos documents avec le Cockpit IA Zayado." });
  return (
    <MarketingLayout>
      <section className="mx-auto grid max-w-6xl gap-10 px-5 pb-16 pt-10 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:pb-24 lg:pt-20">
        <div>
          <p className="mb-4 text-xs font-semibold uppercase tracking-[0.24em] text-gold">Cockpit IA Zayado</p>
          <h1 className="max-w-3xl font-display text-4xl font-bold leading-[1.05] text-white sm:text-6xl">Le cockpit IA pour développer votre entreprise sans vous épuiser.</h1>
          <p className="mt-6 max-w-2xl text-lg leading-relaxed text-offwhite/70">Clarifiez votre vision, organisez vos priorités, développez votre activité et préservez votre équilibre depuis un seul espace.</p>
          <div className="mt-8 flex flex-wrap gap-3"><Link to="/login?next=%2Fonboarding" className="btn-gold inline-flex items-center gap-2 px-5 py-3">Découvrir le Cockpit IA <ArrowRight size={16} /></Link><a href="#fonctionnalites" className="btn-ghost px-5 py-3">Voir comment ça fonctionne</a></div>
          <p className="mt-4 text-xs text-offwhite/45">L’IA prépare. Vous décidez.</p>
        </div>
        <div className="glass-strong relative overflow-hidden rounded-3xl p-3 shadow-2xl"><div className="rounded-2xl border border-white/10 bg-navy-900/80 p-5"><div className="mb-5 flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[0.2em] text-gold">Cockpit Zayado</p><p className="mt-1 font-display text-xl font-bold text-white">Votre prochaine action</p></div><Zap className="text-gold" /></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xs text-offwhite/50">Vision</p><p className="mt-2 text-sm font-semibold text-white">Clarifier mon offre</p><div className="mt-4 h-1.5 rounded-full bg-white/10"><div className="h-full w-2/3 rounded-full bg-gold" /></div></div><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xs text-offwhite/50">Énergie du jour</p><p className="mt-2 text-sm font-semibold text-white">Rythme stable</p><p className="mt-4 text-xs text-emerald-300">3 priorités réalistes</p></div></div><div className="mt-3 rounded-2xl border border-cyan-300/20 bg-cyan-300/5 p-4"><p className="text-xs text-cyan-200">Copilote IA</p><p className="mt-2 text-sm leading-relaxed text-offwhite/80">« Je te propose de préparer le brief de ton offre avant de lancer une nouvelle action. »</p></div></div></div>
      </section>

      <section className="border-y border-white/10 bg-navy-900/40"><div className="mx-auto max-w-6xl px-5 py-14"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-gold">Vous vous reconnaissez ?</p><h2 className="mt-3 max-w-3xl font-display text-3xl font-bold text-white sm:text-4xl">Vous avancez, mais tout repose encore sur votre tête.</h2><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{["Trop d’idées dispersées entre plusieurs outils.", "Des tâches urgentes qui remplacent les vraies priorités.", "Une prospection repoussée quand l’énergie baisse.", "Une activité qui prend trop de place dans votre vie."].map((x) => <div key={x} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4 text-sm leading-relaxed text-offwhite/70">{x}</div>)}</div></div></section>

      <section className="mx-auto max-w-6xl px-5 py-16" id="fonctionnalites"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-gold">Une méthode reliée</p><h2 className="mt-3 font-display text-3xl font-bold text-white sm:text-4xl">Un seul cockpit pour relier votre vision à vos prochaines actions.</h2><p className="mt-4 leading-relaxed text-offwhite/65">Zayado transforme une direction parfois floue en objectifs, actions, opportunités et documents compréhensibles. Vous gardez le sens et la décision.</p></div><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{FEATURES.map(({ icon: Icon, title, text, to }) => <Link key={title} to={to} className="group rounded-2xl border border-white/10 bg-white/[0.03] p-5 transition hover:border-gold/40 hover:bg-white/[0.06]"><Icon className="text-gold" size={20} /><h3 className="mt-4 font-display text-lg font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-relaxed text-offwhite/60">{text}</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-gold">En savoir plus <ArrowRight size={13} className="transition group-hover:translate-x-1" /></span></Link>)}</div></section>

      <section className="bg-[#0f1b3a] py-16"><div className="mx-auto grid max-w-6xl gap-8 px-5 lg:grid-cols-3"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-gold">Comment ça marche</p><h2 className="mt-3 font-display text-3xl font-bold text-white">De la dispersion à une prochaine action.</h2></div>{[["01", "Décrire", "Votre activité, vos objectifs et la difficulté du moment."], ["02", "Structurer", "L’IA propose une structure, une priorité ou un document."], ["03", "Valider", "Vous choisissez ce qui a du sens et passez à l’action."]].map(([n, t, d]) => <div key={n} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><p className="text-2xl font-bold text-gold">{n}</p><h3 className="mt-5 font-display text-xl font-semibold text-white">{t}</h3><p className="mt-2 text-sm leading-relaxed text-offwhite/60">{d}</p></div>)}</div></section>

      <section className="mx-auto grid max-w-6xl gap-10 px-5 py-16 lg:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-gold">Une IA sous contrôle</p><h2 className="mt-3 font-display text-3xl font-bold text-white">L’IA prépare. Vous décidez.</h2><p className="mt-4 leading-relaxed text-offwhite/65">Le Copilote peut clarifier une idée, préparer un brief, proposer une action ou créer un document. Les actions importantes restent sous votre validation.</p><div className="mt-6 space-y-3">{["Contexte de votre activité", "Décisions à valider", "Documents générés à votre demande", "Sauvegarde cloud activable dans Paramètres"].map((x) => <p key={x} className="flex items-center gap-2 text-sm text-offwhite/75"><Check size={15} className="text-emerald-300" />{x}</p>)}</div></div><div className="rounded-3xl border border-cyan-300/20 bg-cyan-300/5 p-7"><ShieldCheck className="text-cyan-200" /><h3 className="mt-5 font-display text-2xl font-semibold text-white">Vos données restent sous votre contrôle.</h3><p className="mt-3 text-sm leading-relaxed text-offwhite/65">Aucun document n’est envoyé dans un cloud externe sans connexion et activation explicites. Vous pouvez désactiver la sauvegarde automatique à tout moment.</p></div></section>

      <section className="border-y border-white/10 bg-white/[0.02] py-16"><div className="mx-auto max-w-6xl px-5"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-gold">Preuves</p><h2 className="mt-3 font-display text-3xl font-bold text-white">Ils retrouvent de la clarté dans leur activité.</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{["Freelance", "Consultant", "Dirigeant de petite entreprise"].map((x) => <div key={x} className="rounded-2xl border border-dashed border-white/20 p-5"><p className="text-xs uppercase tracking-widest text-gold">Témoignage à venir · {x}</p><p className="mt-4 text-sm leading-relaxed text-offwhite/55">Ajoutez ici un retour réel, le problème initial et un résultat vérifiable. Ne publiez pas de chiffre non mesuré.</p></div>)}</div></div></section>

      <section className="mx-auto max-w-4xl px-5 py-16"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-gold">FAQ</p><h2 className="mt-3 font-display text-3xl font-bold text-white">Questions fréquentes sur le Cockpit IA Zayado</h2><div className="mt-8 space-y-3">{FAQ.map(([q, a]) => <details key={q} className="group rounded-2xl border border-white/10 bg-white/[0.03] p-5"><summary className="cursor-pointer list-none font-semibold text-white">{q}<span className="float-right text-gold">+</span></summary><p className="mt-3 max-w-3xl text-sm leading-relaxed text-offwhite/65">{a}</p></details>)}</div></section>

      <section className="mx-auto max-w-6xl px-5 pb-20"><div className="rounded-3xl bg-gradient-to-br from-[#DEC2A3] to-[#F1E2CC] p-8 text-navy-900 sm:p-12"><h2 className="max-w-2xl font-display text-3xl font-bold sm:text-4xl">Votre entreprise mérite plus de clarté, pas plus de pression.</h2><p className="mt-3 max-w-xl text-sm/relaxed text-navy-900/75">Commencez par structurer votre prochaine priorité. Le reste se construit étape par étape.</p><Link to="/login?next=%2Fonboarding" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-navy-900 px-5 py-3 text-sm font-semibold text-white">Découvrir le Cockpit IA <ArrowRight size={16} /></Link></div></section>
    </MarketingLayout>
  );
}
