import React from "react";
import { Helmet } from "react-helmet-async";
import { ArrowRight, Building2, BriefcaseBusiness, Coffee, Globe2, Hotel, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { PublicHeader, UnifiedFooter } from "./LandingHub";

const NEGOCIES = [
  [ShieldCheck, "Protection professionnelle", "Des conditions négociées lorsque le volume ZAYADO permet d'obtenir un avantage réel."],
  [Building2, "Outils et services pro", "Banque, SaaS, coworking ou autres services utiles à votre activité, selon les accords disponibles."],
  [BriefcaseBusiness, "Conditions collectives", "La mutualisation reste la mécanique : ZAYADO négocie pour plusieurs plutôt que chacun dans son coin."],
];
const TRAVEL = [
  [Coffee, "Coworking", "Accéder à des espaces de travail dans les villes où vous vous déplacez."],
  [Hotel, "Hôtels business", "Des offres ponctuelles ou conditions négociées chez les partenaires sélectionnés."],
  [Globe2, "Business Travel", "Réunir travail, mobilité et découverte sans créer un nouveau rayon compliqué."],
];
export default function Avantages(){return <div className="min-h-screen flex flex-col" style={{background:"var(--zayado-cream)"}}>
  <Helmet><title>Avantages ZAYADO | Tarifs négociés et offres pour entrepreneurs</title><meta name="description" content="Avantages ZAYADO : tarifs négociés pour les indépendants et petites structures, plus des offres ponctuelles de coworking, hôtels et Business Travel."/><link rel="canonical" href="https://zayado.net/avantages"/><meta property="og:title" content="Avantages ZAYADO | Négocier mieux, entreprendre plus simplement"/><meta property="og:description" content="Des conditions collectives négociées et des offres du moment pensées pour les indépendants."/><meta property="og:image" content="https://zayado.net/zayado-og.jpg"/></Helmet>
  <PublicHeader/>
  <main className="flex-1">
    <section className="bg-[#0c1d33] text-white"><div className="max-w-[1180px] mx-auto px-6 py-16 sm:py-20"><span className="text-[11px] uppercase tracking-[.18em] text-[#d4b982] font-bold">Avantages ZAYADO</span><h1 className="mt-4 max-w-4xl text-4xl sm:text-5xl font-bold">Des conditions négociées pour entreprendre <span className="text-[#d4b982]">plus simplement.</span></h1><p className="mt-5 max-w-2xl text-base sm:text-lg leading-7 text-white/70">La mutualisation reste notre mécanique de fond : lorsque plusieurs membres ont le même besoin, ZAYADO négocie des conditions collectives. À côté, les offres du moment permettent de découvrir des partenaires sans engagement permanent.</p></div></section>
    <section className="max-w-[1180px] mx-auto px-6 py-14"><div className="grid md:grid-cols-3 gap-5">{NEGOCIES.map(([I,t,d])=><article key={t} className="rounded-3xl border bg-white p-7" style={{borderColor:"var(--zayado-border)"}}><div className="w-11 h-11 rounded-xl bg-[#f3e9d0] text-[#b89855] grid place-items-center"><I size={20}/></div><h2 className="mt-5 text-xl font-bold text-[#1a3a6e]">{t}</h2><p className="mt-2 text-sm leading-6 text-[#6b6358]">{d}</p></article>)}</div></section>
    <section className="bg-white border-y" style={{borderColor:"var(--zayado-border)"}}><div className="max-w-[1180px] mx-auto px-6 py-14"><div className="flex flex-wrap items-end justify-between gap-4"><div><span className="text-[11px] uppercase tracking-[.18em] text-[#b89855] font-bold">Offres du moment</span><h2 className="mt-2 text-3xl font-bold text-[#1a3a6e]">Le côté « deal » de ZAYADO.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#6b6358]">Des offres limitées, clairement étiquetées, notamment pour les entrepreneurs qui travaillent dans plusieurs villes.</p></div><span className="rounded-full bg-[#f3e9d0] px-3 py-1 text-xs font-semibold text-[#1a3a6e]">Offre limitée</span></div><div className="mt-8 grid md:grid-cols-3 gap-5">{TRAVEL.map(([I,t,d],i)=><article key={t} className="rounded-2xl overflow-hidden border" style={{borderColor:"var(--zayado-border)"}}><div className="h-36 bg-gradient-to-br from-[#1a3a6e] to-[#102945] grid place-items-center text-[#d4b982]"><I size={38} strokeWidth={1.4}/></div><div className="p-5"><p className="text-[10px] uppercase tracking-[.16em] text-[#b89855]">Pilote {i+1}</p><h3 className="mt-1 font-bold text-[#1a3a6e]">{t}</h3><p className="mt-2 text-sm leading-6 text-[#6b6358]">{d}</p><p className="mt-4 text-xs text-[#6b6358]">Disponibilité selon les partenaires et les villes.</p></div></article>)}</div></div></section>
    <section className="max-w-[900px] mx-auto px-6 py-14 text-center"><Sparkles className="mx-auto text-[#b89855]"/><h2 className="mt-3 text-3xl font-bold text-[#1a3a6e]">Une offre claire plutôt qu'un catalogue sans fin.</h2><p className="mt-3 text-sm leading-6 text-[#6b6358]">ZAYADO privilégie quelques accords réels, vérifiés et utiles. Les économies affichées doivent être vérifiables ; aucun chiffre décoratif.</p><Link to="/nos-services" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#1a3a6e] px-5 py-3 text-sm font-bold text-white">Voir aussi les Services Pro <ArrowRight size={16}/></Link></section>
  </main><UnifiedFooter/></div>}
