import React from "react";
import { Helmet } from "react-helmet-async";
import { Link, useParams } from "react-router-dom";
import { ArrowRight, Check, ChevronRight } from "lucide-react";
import { PublicHeader, UnifiedFooter } from "./LandingHub";

const DATA={
  "finance-pilotage":{title:"Pilotage financier pour indépendants et petites structures",short:"Finance & pilotage",desc:"Structurez votre trésorerie, vos indicateurs et vos décisions avec un accompagnement adapté à la réalité d'une petite structure.",points:["Lecture de la trésorerie et des flux","Tableaux de bord et indicateurs utiles","Analyse de marge et de rentabilité","Préparation des décisions financières"],cta:"Parler de mon besoin",path:"/services/finance-pilotage"},
  "gestion-organisation":{title:"Gestion & organisation pour entrepreneurs",short:"Gestion & organisation",desc:"Réduisez la charge administrative et rendez votre fonctionnement plus clair grâce à des méthodes adaptées à votre activité.",points:["Organisation administrative","Suivi des échéances","Facturation et documents","Processus simples et reproductibles"],cta:"Faire mon diagnostic",path:"/services/gestion-organisation"},
  "developpement":{title:"Développement commercial pour indépendants",short:"Développement & acquisition",desc:"Clarifiez vos priorités commerciales et structurez vos actions d'acquisition, de marketing et de suivi des résultats.",points:["Positionnement et offre","Acquisition et prospection","Marketing opérationnel","Suivi des actions et résultats"],cta:"Définir ma priorité",path:"/services/developpement"},
  "structuration":{title:"Structurer son projet entrepreneurial avec ZAYADO",short:"Création & structuration",desc:"Avant d'investir du temps et de l'argent, clarifiez votre projet, son modèle économique et vos prochaines décisions.",points:["Cadrage de l'idée","Business model et offre","Analyse des priorités","Plan d'action réaliste"],cta:"Valider mon projet",path:"/services/structuration"}
};
export default function ServiceDetail(){const {slug}=useParams();const d=DATA[slug]||DATA["finance-pilotage"];return <div className="min-h-screen flex flex-col" style={{background:"var(--zayado-cream)"}}><Helmet><title>{d.title} | ZAYADO</title><meta name="description" content={`${d.desc} Découvrez l'accompagnement professionnel ZAYADO.`}/><link rel="canonical" href={`https://zayado.net${d.path}`}/><meta property="og:title" content={`${d.short} | ZAYADO`}/><meta property="og:description" content={d.desc}/><meta property="og:image" content="https://zayado.net/zayado-og.jpg"/><script type="application/ld+json">{JSON.stringify({"@context":"https://schema.org","@type":"Service","name":d.short,"provider":{"@type":"Organization","name":"ZAYADO","url":"https://zayado.net"},"description":d.desc})}</script></Helmet><PublicHeader/><main className="flex-1"><section className="bg-[#0c1d33] text-white"><div className="max-w-[1100px] mx-auto px-6 py-16 sm:py-20"><Link to="/nos-services" className="text-sm text-white/55 hover:text-white">← Tous les Services Pro</Link><p className="mt-8 text-[11px] uppercase tracking-[.18em] text-[#d4b982] font-bold">ZAYADO Services Pro</p><h1 className="mt-3 max-w-4xl text-4xl sm:text-5xl font-bold leading-tight">{d.title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/70">{d.desc}</p><Link to={`/contact?service=${slug}`} className="mt-7 inline-flex items-center gap-2 rounded-xl bg-[#d4b982] px-5 py-3 text-sm font-bold text-[#0c1d33]">{d.cta} <ArrowRight size={16}/></Link></div></section><section className="max-w-[1100px] mx-auto px-6 py-14 grid lg:grid-cols-[1fr_.8fr] gap-10"><div><h2 className="text-3xl font-bold text-[#1a3a6e]">Ce que l'accompagnement couvre</h2><ul className="mt-7 grid gap-4">{d.points.map(p=><li key={p} className="flex gap-3 rounded-2xl border bg-white p-4" style={{borderColor:"var(--zayado-border)"}}><Check className="shrink-0 text-[#b89855]" size={18}/><span className="text-sm leading-6">{p}</span></li>)}</ul></div><aside className="rounded-3xl bg-[#f3e9d0] p-7 h-fit"><p className="text-xs uppercase tracking-[.16em] font-bold text-[#b89855]">Comment ça marche</p><h2 className="mt-2 text-2xl font-bold text-[#1a3a6e]">Un parcours simple.</h2><ol className="mt-6 grid gap-4 text-sm"><li><b>1. Diagnostic</b><br/><span className="opacity-65">Vous décrivez votre situation et votre priorité.</span></li><li><b>2. Cadrage</b><br/><span className="opacity-65">Nous définissons le périmètre et le bon intervenant.</span></li><li><b>3. Mission</b><br/><span className="opacity-65">La prestation est réalisée par ZAYADO, un collaborateur ou un partenaire adapté.</span></li></ol><Link to="/nos-services#diagnostic" className="mt-6 inline-flex items-center gap-1 text-sm font-bold text-[#1a3a6e]">Faire le diagnostic <ChevronRight size={15}/></Link></aside></section></main><UnifiedFooter/></div>}
